

env = { term = "xterm-256color" }


[window]
# decorations = "None"
opacity = 0.96
dynamic_padding = true


[font]
normal = { family = "MonaspiceNe Nerd Font", style = "Light" }
italic = { family = "MonaspiceRn Nerd Font", style = "Light" }
size = 8
offset = { y = 2 }


[cursor]
style = { shape = "Block", blinking = "On" }
vi_mode_style = { shape = "Block", blinking = "On" }

[general]


live_config_reload = true
import = ["~/dotfiles/.config/alacritty/themes/themes/one_dark.toml"]
