theme = "kanagawa" 

[editor]
line-number = "relative"
cursorline = true
middle-click-paste = false
preview-completion-insert = false
completion-replace = true
bufferline = "multiple"
color-modes = true
end-of-line-diagnostics = "hint"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.statusline]
left = ["mode", "version-control"]
center = ["file-name"]
right = ["diagnostics", "selections", "position", "file-type"]
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "VISUAL"

[editor.lsp]
display-messages = true
display-inlay-hints = false

[editor.inline-diagnostics]
cursor-line = "warning" # show warnings and errors on the cursorline inline

[editor.whitespace.render]
space = "none"
tab = "none"
newline = "none"

[editor.whitespace.characters]
# space = "·"
# nbsp = "⍽"
# tab = "→"
# newline = "⏎"
# tabpad = "→" # Tabs will look like "→···" (depending on tab width)

[editor.indent-guides]
render = true
character = "▏" # Some characters that work well: "▏", "╎", "┆", "┊", "⸽"
skip-levels = 1


### KEYBINDINGS

[keys.normal]
# C-s = ":w"
# lsp
[keys.normal.space]
l = {a = "code_action", f = ":format"}

[keys.normal.space.g]
f = "changed_file_picker"
g = [":new", ":insert-output lazygit", ":buffer-close!", ":redraw"]

# [keys.insert]
# C-s = ":w"

