theme = "kanagawa" 

[editor]
line-number = "relative"
cursorline = true
middle-click-paste = false
completion-replace = true
bufferline = "multiple"
color-modes = true
end-of-line-diagnostics = "hint"
auto-format = true
path-completion = true


auto-completion = true
preview-completion-insert = false

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false
git-ignore = false

[editor.statusline]
left = ["mode", "version-control"]
center = ["file-name"]
right = ["diagnostics", "selections", "position", "file-type"]
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "VISUAL"

[editor.lsp]
display-messages = true
display-inlay-hints = false

[editor.inline-diagnostics]
cursor-line = "warning" # show warnings and errors on the cursorline inline, multiple lines
other-lines = "disable"

[editor.whitespace.render]
# space = "all"
# tab = "all"
# newline = "all"

# [editor.whitespace.characters]
# # space = "·"
# nbsp = "⍽"
# tab = "→"
# newline = "⏎"
# tabpad = "→" # Tabs will look like "→···" (depending on tab width)

[editor.indent-guides]
render = true
character = "▏" # Some characters that work well: "▏", "╎", "┆", "┊", "⸽"
skip-levels = 1


### KEYBINDINGS

[keys.normal]
# C-s = ":w" # Ctrl + S to save
C-h = "jump_view_left"
C-j = "jump_view_down"
C-k = "jump_view_up"
C-l = "jump_view_right"
C-e = "expand_selection"
"C-." = "repeat_last_motion"
"{" = "goto_prev_paragraph"
"}" = "goto_next_paragraph"

[keys.normal.space]
# LSP options
l = {a = "code_action", f = ":format", d = "goto_definition"}
# Open Yazi from helix
e = [
    ':sh rm -f /tmp/unique-file',
    ':insert-output yazi %{buffer_name} --chooser-file=/tmp/unique-file',
    ':insert-output echo "\x1b[?1049h\x1b[?2004h" > /dev/tty',
    ':open %sh{cat /tmp/unique-file}',
    ':redraw',
]
# Alpha dashboard
a = { q = ":quit-all", c = ":config-open" }

[keys.normal.space.b]
f = "buffer_picker"
o = ":buffer-close-others"
c = ":buffer-close"
x = ":buffer-close!"

[keys.normal.space.g]
f = "changed_file_picker"
g = [":new", ":insert-output lazygit", ":buffer-close!", ":redraw"]
b = ":echo %sh{git blame -L %{cursor_line},+1 %{buffer_name}}"

[keys.insert]
# C-s = ":w"
"C-space" = "completion" 
